# Site settings
title: Demian Neidetcher 
email: demian0311@gmail.com 
#url: "http://neidetcher.com" # the base hostname & protocol for your site
#port: "4000"
#host: "neidetcher.com"
#baseurl: "/" # does not include hostname
#show_dir_listing: false
description: > # this means to ignore newlines until "baseurl:"
    Father, husband and computer person

# Build settings

#markdown: redcarpet
#highlighter: pygments
highlighter: rouge

